### ISSUE TITLE
투어 디테일 페이지 제작하기

### ISSUE THREAD

**Issue by hae2ni** [GOSOPT-CDS-TEAM4/MyRealTripClient#33]
## Description
Tour_detail page 제작 관련 사항들입니다. 

## Todo
- [ ] 디테일 페이지 헤더 제작 #32 
- [ ] 디테일 페이지 사진 #33
- [ ] 디테일 페이지 제목 및 소개 섹션 제작 #34
- [ ] 디테일 페이지 취소, 예약 소개 섹션 제작 #35
- [ ] 디테일 페이지 서비스 섹션 제작 #36
- [ ] 디테일 페이지 Q&A 섹션 제작 #37
- [ ] 디테일 페이지 이용후기 섹션 제작 #38
- [ ] 디테일 페이지 상품정보 섹션 제작 #39
- [ ] 디테일 페이지 코스소개 섹션 제작 #40
- [ ] 디테일 페이지 이용안내 섹션 제작 #41
- [ ] 디테일 페이지 구글맵 연동 #42
- [ ] 디테일 페이지 비슷한상품 섹션 제작 #43
- [ ] 디테일 페이지 프로팅바 제작 #44
- [ ] 공통 푸터

## 개발 기한

본인의 상황을 판단했을 때 Best, Normal, Worst를 판단해서 작성해주세요! 
이때 실제 기한은 Normal~Worst로 생각하고 진행해주시고, 만일 자신이 맡는 feature가 부담된다면, 바로 팀원들에게 도움을 요청해주세요!

- Best: 1.5d
- Normal: 2.5d
- Worst: 3.5-4d

## Milestone, Assignees, Labels
이슈를 등록하기 전, 위 세 사항을 확실하게 등록해주세요!!
