### ISSUE TITLE
Tour Page 뷰 구현하기

### ISSUE THREAD

**Issue by Geun-Oh** [GOSOPT-CDS-TEAM4/MyRealTripClient#64]
## Description
어떤 기능인가요? 설명을 작성해주세요

## Todo
- [ ] 헤더 구현
- [ ] 메인 네비게이션 바 구현
- [ ] 그리드 메뉴 바 구현
- [ ] 마이리얼 매거진 섹션 구현
- [ ] 베스트 리뷰 인기 투어 상품 섹션 구현
- [ ] 날짜 없이 예약 가능한 상품 섹션 구현
- [ ] 파리 최저가 보장 섹션 구현
- [ ] 푸터 구현

## 개발 기한

본인의 상황을 판단했을 때 Best, Normal, Worst를 판단해서 작성해주세요! 
이때 실제 기한은 Normal~Worst로 생각하고 진행해주시고, 만일 자신이 맡는 feature가 부담된다면, 바로 팀원들에게 도움을 요청해주세요!

- Best: 1d
- Normal: 1.5d
- Worst: 2d

## Milestone, Assignees, Labels
이슈를 등록하기 전, 위 세 사항을 확실하게 등록해주세요!!

**Comment by Geun-Oh** [comment]
#72
