### ISSUE TITLE
네브 버튼 모달 리팩토링

### ISSUE THREAD

**Issue by eunbeann** [GOSOPT-CDS-TEAM4/MyRealTripClient#73]
## Description
어떤 기능인가요? 설명을 작성해주세요

## Todo
- [ ] 버튼 클릭에 따른 컨텐츠 렌더링
- [ ] 달력 클릭 그리드 적용
- [ ] 자잘한 뷰 수정
- [ ] 가독성 코드 리팩토링

## 개발 기한

본인의 상황을 판단했을 때 Best, Normal, Worst를 판단해서 작성해주세요! 
이때 실제 기한은 Normal~Worst로 생각하고 진행해주시고, 만일 자신이 맡는 feature가 부담된다면, 바로 팀원들에게 도움을 요청해주세요!

- Best: 1d
- Normal: 1d 1/4
- Worst: 2d

## Milestone, Assignees, Labels
이슈를 등록하기 전, 위 세 사항을 확실하게 등록해주세요!!
