### ISSUE TITLE
투어리스트페이지 데이터 패칭

### ISSUE THREAD

**Issue by eunbeann** [GOSOPT-CDS-TEAM4/MyRealTripClient#79]
## Description
어떤 기능인가요? 설명을 작성해주세요
-투어리스트 페이지 데이터 패칭

## Todo
- [ ] axios로 get 해오기 => get 자체 테스트
- [ ] 조건에 맞게 값 지정해주기
- [ ] 지정해준 값으로 get 해오기

## 개발 기한

본인의 상황을 판단했을 때 Best, Normal, Worst를 판단해서 작성해주세요! 
이때 실제 기한은 Normal~Worst로 생각하고 진행해주시고, 만일 자신이 맡는 feature가 부담된다면, 바로 팀원들에게 도움을 요청해주세요!

- Best:
- Normal:
- Worst:

## Milestone, Assignees, Labels
이슈를 등록하기 전, 위 세 사항을 확실하게 등록해주세요!!
